### ISSUE TITLE
Unable to save "Twilio Auth Token" when creating a new account.

### ISSUE THREAD

**Issue by spreaderman** [bludesign/FaxServer#12]
I have created an account.  I have added my Twilio Account SID.  When I SUBMIT, the SID is shown.  When I try to add my Twilio Auth Token by hitting the SUBMIT button, I receive no error but an empty input box is returned.

When I send a test fax I get the error: 
401
Unauthorized
Twilio reponse error 

Any help appreciated.

I am using twilio in japan.  https://jp.twilio.com/

**Comment by j2tanning** [comment]
The auth token does disappear after Submitting, but it does save it. Are you by chance on a free account with Twilio? I don't think they allow access to API on a trial.

**Comment by spreaderman** [comment]
Not a free / trial account.

**Comment by chandlerhuff** [comment]
The Twilio Auth Token does not show when saved but it is saved the newest version fixes this and will now show that it has been saved. There are a lot of reasons you could get a 401 error other then an incorrect auth token the newest version will show the error Twilio gives instead of just 401. Run `docker-compose pull` to get the newest version.

**Comment by spreaderman** [comment]
Tried above.  Did docker-compose all.  I am running the latest version.  I cannot see that the token is saved.  Same as before.  Same error too. This should be left as an open issue for others to see until fixed.
